### ISSUE TITLE
view download files

### ISSUE THREAD

**Issue by baba2580** [xinxin8816/heroku-ariang-21vianet#10]
Cannot GET /downloads//

**Comment by xinxin8816** [comment]
Input APP Secret first and then click view download files.

**Comment by baba2580** [comment]
Inserted APP Secret clicked on view download files get this msg

Cannot GET /downloads/YmFiYTFAaGVyb2t1/

**Comment by xinxin8816** [comment]
Two possible reasons:
1. Wrong APP secret.
2. There have no tasks completed.
