### ISSUE TITLE
apps gets idle in middle  of download

### ISSUE THREAD

**Issue by Druboo666** [xinxin8816/heroku-ariang-21vianet#12]
apps gets ideal in middle of download and never complete the download of large file as the files get deleted.
i have configured r-clone correctly cause small file can be downloaded and gets uploaded to G-drive but the large file never completes the download because of idling issue

**Comment by xinxin8816** [comment]
When there have task, APP will make request to prevent idling. Please confirm that is idleing, not memory overflow.

If idle definitely, try
1. Reduce tasks to reduce resource usage
2. Reduce request of prevent idling interval in index.js

**Comment by abretas** [comment]
> When there have task, APP will make request to prevent idling. Please confirm that is idleing, not memory overflow.
> 
> If idle definitely, try
> 
> 1. Reduce tasks to reduce resource usage
> 2. Reduce request of prevent idling interval in index.js

Hi xinxin8816 I´m having the same problem when i try to download a large file, ex; 60 gb the heroku disconnect and i lost all the progress of download.

How can i configure the  index.js to prevent this error.
