### ISSUE TITLE
need docker support and ZIP feature

### ISSUE THREAD

**Issue by rsoorajs** [xinxin8816/heroku-ariang-21vianet#13]
could you add docker support and then deploy to heroku as a docker image.heroku will not ban then.

**Comment by xinxin8816** [comment]
Nope. Conversely, using Docker will consume more resources, making your account more easily to be ban, and also affect users who use the same Docker image.

**Comment by rsoorajs** [comment]
okay.what about zip feature ?

**Comment by xinxin8816** [comment]
Unzip does not seem to be necessary, you can try [Heroku-Rclone-21vianet](https://github.com/xinxin8816/heroku-rclone-21vianet)

Or what other? After Aria2 download, auto unzip and then upload through rclone?

**Comment by rsoorajs** [comment]
no no.i dont meant unzip.i mean zip.
if a torrent file contain 20 parts.i have download 20 files one by one.if there is an option for zipping them in to one,i can download the whole file in one click.thats i meaned

**Comment by xinxin8816** [comment]
Good idea! I have added the ZIP feature, please deploy by [Dev branch](https://github.com/xinxin8816/heroku-ariang-21vianet/tree/Dev) to test it.

**Comment by rsoorajs** [comment]
Its auto uploading,and not working for me.i mean if there is a checkbox for Zip while downloading,torrents,thats good.because we dont want to zip everyfile which we are leeching.also the uploading to the gdrive doesnt works for me.i put the correct rclone value and still it didnt uploads.the orginal branch of maples working for me.Thanks

**Comment by xinxin8816** [comment]
Blank rclone config or destination, only auto zip will activate. 
Fill in rclone config and destination, it will auto zip in download folder, also upload the original file by rclone at the same time. This does not affect each other.

checkbox while downloading need modify AriaNG , that may be a big project, and I don't have time to do this now.

rclone working well now, if not work for you, try to view logs to find reasons.

**Comment by rsoorajs** [comment]
ok.i will try that

**Comment by xinxin8816** [comment]
Dockerize the APP has been completed.
