### ISSUE TITLE
Error Description: error.resource.notfound.max-file-not-found

### ISSUE THREAD

**Issue by sagirisayang** [xinxin8816/heroku-ariang-21vianet#14]
I found a weird issue.
I use both this version and maple3142's version

When I wanted to torrent anime from hi10anime, the maple3142's did it well and the download was able to be started
But when I used this version, the download stopped immediately after downloading the .torrent file.
When I checked in the stopped tab, it showed the name of the torrent and the size, but it showed red X icon, when it checked the details:

Task Name: [Hi10]_Honzuki_no_Gekokujou_[810p]
Task Size: 1,002.90 MB
Task Status: Error Occurred (4)
Error Description: error.resource.notfound.max-file-not-found

Actually, this happened quite often when downloading from hi10anime, so I have to use the maple3142's version when this issue occurs (sometimes it works with this version, but sometimes it doesn't)

Does this have a relation with the config or is it a bug or something?

If you want to test the files that I tested above:
https://hi10anime.com/archives/85775
(Must register to hi10anime first, then download the batch)

**Comment by xinxin8816** [comment]
Try to edit max-file-not-found in aria2c.conf, value 0 may be work.

**Comment by sagirisayang** [comment]
Thanks for replying.

I will test it.

**Comment by sagirisayang** [comment]
Okay, I just tested it, and it works :D
But I didn't re-deploy aria2c.conf to Heroku, I just changed the "max file not found try times" in the AriaNg settings, and it worked well. I don't know whether it's permanent or not (after idle/daily reset), but it's pretty okay for me.

Thanks again for helping me
