### ISSUE TITLE
Not seeding

### ISSUE THREAD

**Issue by eliasbenb** [xinxin8816/heroku-ariang-21vianet#15]
The app doesn't seed any torrents. Do you know why?

**Comment by xinxin8816** [comment]
I don't understand what your means. Torrents download is working well now.

**Comment by eliasbenb** [comment]
It downloads perfectly fine, but uploading doesn't work. It uploads 0 bytes.

**Comment by xinxin8816** [comment]
Go to Heroku Dashboard, and view application logs to find reasons.
