### ISSUE TITLE
Apps don´t Download Large Torrent Files

### ISSUE THREAD

**Issue by abretas** [xinxin8816/heroku-ariang-21vianet#16]
Hi xinxin8816

Could you help me.

I am trying to download some large torrent files. Some with more than 60gb but even before the download is finished the application restarts and I lose all the work already done.

I saw that in another post you said that you have some configuration that has to be done to solve this problem. If I'm not mistaken in the index.js file

Which part of this file has to be changed so that this problem does not happen again.

**Comment by xinxin8816** [comment]
“setTimeout” in index.js, setting smaller values _**MAYBE**_ useful, but your Heroku account may be more likely to be suspend.
Paying for Heroku Hobby Dyno is more indestructible, but Heroku Dyno reset every 24 hours is inevitable.

**Comment by abretas** [comment]
I will try this. Thanks xinxin8816.
