### ISSUE TITLE
How to use service accounts

### ISSUE THREAD

**Issue by ckvbalusu** [xinxin8816/heroku-ariang-21vianet#19]
Sorry for this noob Question. I don't understand some points in README.

" Using service account setup with Gclone to break Google Drive 750GB limit, or easier connect to folder or Team Drive by destination ID. Create a new folder, such as /accounts/, upload your json in it. Open rclone config and edit service_account_file_path = /app/accounts/ as the json paths."

--> is Gclone used in this repo instead of Rclone?
--> I have 100 SA i copied them to /accounts too
      but 
        service_account_file =  "what this should be "
        service_account_file_path = /app/accounts/
I cant understand the RCLONE docs too at  this "service_account_file" yeah it also a JSON Path but where to get that JSON from can you please assist me if you know

Thanks 😀

**Comment by xinxin8816** [comment]
1. this repo used rclone and compatible with gclone & 21vianet features
2. service_account_file = "/app/accounts/xxx.json" 
xxx.json is anyone of 100 json. that json to be use to init upload task.

**Comment by xinxin8816** [comment]
More about [service account support](https://rclone.org/drive/#service-account-support) in rclone.

**Comment by ckvbalusu** [comment]
type = drive
client_id = ...............
client_secret = ........................
scope = drive
service_account_file = E:\blabla\accounts\bla.json
service_account_file_path = E:\bla\accounts
team_drive = xxxxxxxxxxxxx
Finally it Should look like this right ?
I have Another doubt i used this app without SA but while downloading big sized torrents over 100 gigs App is getting restarted ? and entire progress is lost any way to fix this ?

**Comment by xinxin8816** [comment]
1. Json path is /app/account/... In heroku, not local path.
2. Reduce task to prevent memory overflow. 
I have an idea to save download progress, but have no time to achieve it now.

**Comment by ckvbalusu** [comment]
https://github.com/xinxin8816/heroku-ariang-21vianet/issues/16#issuecomment-634009209

Will this work ?

**Comment by xinxin8816** [comment]
Yep, #16 can prevent idle restart, but not memory overflow. Usually big size task is restart by overflow.

**Comment by ckvbalusu** [comment]
ok
5 mins is lowest right in your Repo but in Maple3142's one He gave it 15 mins. Now can i give 15 min for your one too. As His Repo is working for me for ~250 GB Torrents too :)

**Comment by xinxin8816** [comment]
You can try it

**Comment by ckvbalusu** [comment]
Thanks for Support
