### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by qingchencjg** [xinxin8816/heroku-ariang-21vianet#21]
我在vps上部署了https://github.com/P3TERX/aria2.sh这个程序，但是我想实现下载后同时上传到多个OneDrive或Google盘，想请教下这个程序是如何实现的，自己也不懂编程语言，想问下这个程序可不可以搭建在vps上，或者P3TERX的怎么改才能实现，谢谢

**Comment by xinxin8816** [comment]
Sorry, your request exceeds support of this project.
