### ISSUE TITLE
Heroku Deploy Issue

### ISSUE THREAD

**Issue by pctechkid** [xinxin8816/heroku-ariang-21vianet#22]
Heroku automatically suspends app right after deployment. Havent even used it once.

**Comment by xinxin8816** [comment]
View logs to find the reason.

**Comment by pctechkid** [comment]
> View logs to find the reason.

I did and everything is fine during deployment phase and no problem regarding the app itself. The problem is that heroku insta-ban the app. I supposed they have detected the repo which are related with aria2 and bans them right after being deployed.

Please try to deploy your app now on a FRESH heroku account and you'll see they'll just suspend it.

**Comment by pctechkid** [comment]
I'm hoping you could make some workaround this since this is such a great app.

**Comment by xinxin8816** [comment]
That sounds terrible, but I tested with a new account and APP works well.

**Comment by pctechkid** [comment]
> That sounds terrible, but I tested with a new account and APP works well.

You mean heroku didn't ban fresh app right after you deployed?

Now that's kind of weird since Ive tried making different new accounts hoping I could deploy without getting suspended, and even tried different repos and forks of heroku aria2 including yours, and with no luck, they all resulted the same getting suspended.
