### ISSUE TITLE
Rclone config for ncov

### ISSUE THREAD

**Issue by maspodil** [xinxin8816/heroku-ariang-21vianet#3]
Hello,how to create a rclone config for ncov one drive?As,it wants admins right to access one drive @xinxin8816

**Comment by xinxin8816** [comment]
Sorry, I don't know what is 'ncov one drive'.

**Comment by maspodil** [comment]
You can get 5tb one drive from this link but you can't seem to create a rclone config in order to download torrents using your app 
https://zhuanlan.zhihu.com/p/107162804 @xinxin8816

**Comment by xinxin8816** [comment]
OK, it working for OneDrive definitely, no matter what domain.

**Comment by xinxin8816** [comment]
Unless this domain admin don't allow Azure Api.

**Comment by maspodil** [comment]
but how to create a rclone config? @xinxin8816

**Comment by xinxin8816** [comment]
Please follow with **[README](https://github.com/xinxin8816/heroku-aria2c-21vianet#mount-cloud-drive-with-rclone-%E6%8C%82%E8%BD%BD%E7%BD%91%E7%9B%98)**

**Comment by xinxin8816** [comment]
Setup on local computer, then you will have _rclone.conf_ ,find out it and do the next.

**Comment by maspodil** [comment]
Again,it won't work as that account doesn't allow rclone run on office that's why I am asking if anyone could help me out?
![Capture](https://user-images.githubusercontent.com/62073132/76636490-28e39480-656f-11ea-8833-95efa94e8793.PNG)
@xinxin8816

**Comment by xinxin8816** [comment]
Do you apply the API permissions in Azure? If you do but not work, the domain admin NOT allow Azure API.

**Comment by xinxin8816** [comment]
Carefully, Follow [Rclone Document](https://rclone.org/onedrive/#getting-your-own-client-id-and-key) again.

**Comment by maspodil** [comment]
It won't work and I did read the document again @xinxin8816 
![Capture](https://user-images.githubusercontent.com/62073132/76676950-9f73a700-65ee-11ea-8fb6-2a46064ada51.PNG)

**Comment by xinxin8816** [comment]
OK, It seem the domain admin of nCov.office.gy NOT allow Azure API, so you can't mount it with rclone.

**Comment by maspodil** [comment]
yes that's what I am trying to say,so is this account useless to download torrent?

**Comment by xinxin8816** [comment]
Yes, you should use another account.

**Comment by maspodil** [comment]
okay,it seems to waste of this account and if you don't mind can you recommend any other site to get onedrive 5tb? @xinxin8816

**Comment by xinxin8816** [comment]
Sorry, I won’t provide suggestions about this.

**Comment by maspodil** [comment]
okay
