### ISSUE TITLE
how to view ondrive upload process

### ISSUE THREAD

**Issue by N30Z3N** [xinxin8816/heroku-ariang-21vianet#4]
I opened rclone web ui from my pc but it does't show any progress going on as i have downloaded tst files so how can view the process

**Comment by xinxin8816** [comment]
Viewing process is unnecessary usually, most tasks will be completed by themselves, so Rclone Web UI has been removed.
By the way, you can login Heroku Dashboard, find real-time printing of upload process in application log.
