### ISSUE TITLE
How to restrict parallel uploads in rclone Heroku

### ISSUE THREAD

**Issue by N30Z3N** [xinxin8816/heroku-ariang-21vianet#5]
since rclone transfers 4 files at a time it takes ages to transfer 
there is a command --transfers=x that can reduce the transfer numbers
 but how to change that value for rclone in heroku aria ??????????

**Comment by xinxin8816** [comment]
` --transfers=x ` is invalid in Heroku Ariang, each download task use an independent rclone upload process.
Try to reduce the number of download tasks completed at the same time.

**Comment by xinxin8816** [comment]
But if one of your download task includes many files, you can edit `on-complete.sh` using `--transfers=x` to reduce the transfer numbers.

**Comment by N30Z3N** [comment]
On local machine ?

**Comment by xinxin8816** [comment]
Nope, fork and edit in github, and than deploy in your own repo.

**Comment by cyouakari** [comment]
I wrote you an email, please check
